repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace # trim trailing whitespace
    -   id: fix-byte-order-marker # removes UTF-8 byte order marker
    -   id: end-of-file-fixer # makes sure files end in a newline
    -   id: check-case-conflict # check for files with names that conflict on case-insensitive filesystems
    -   id: check-merge-conflict # check for files that contain merge conflict strings
    -   id: check-json # check for JSON syntax errors
    -   id: check-toml # check for TOML syntax errors
    -   id: check-yaml # check for syntax errors in yaml files
    -   id: check-added-large-files # check for large files added to git
    -   id: pretty-format-json # pretty format json files