# Based on cookiecutter-hypermodern-python

name: labeler
description: Automatically label issues and pull requests

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v4.1.0
        with:
          skip-delete: true
